218-reduced-basis-module-document-fails-to-execute-in-jupyter
feelpp/book.feelpp.org pull request #219
Opened 2022-11-07 16:03 UTC by thomas-saigre

- [ ] #218
- fix errors due to bad xref or include

2022-11-07 16:17 UTC, prudhomm requested changes
the testcase is never presented I think. 
Recall the equations and the objectives from a mathematical point of view.

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +config = feelpp.globalRepository("reducedbasis")
use `localRepository("reducedbasis")` for jupyter

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +config = feelpp.globalRepository("reducedbasis")
or `localRepository("")`

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +- `time_dependant` : is the case stationnary or transient ? (for now always to `False`)
type : dependent (e not a)

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +config_file = "thermal-fin.cfg"
this is not robust. Do you create the file ? or should it be available somewhere ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +cfg = feelpp.readCfg(config_file)
what is this function `readCfg` ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +----
no expected output provided ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +----
no output provided ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +----
what should we expect ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +----
should we expect something ?
print the parameter may be ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +[source, python]
describe the next block with respect to the math (affine decomposition...)

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +[reducedbasis] Constant of continuity : 1.0000000000000018
continuity and coercivity are the same ? does it mean that the parameter for use is the one for the scalar product ?

2022-11-07 16:17 UTC, prudhomm commented on docs/user/modules/python/pages/pyfeelppmor/reducedbasis.adoc
> +[reducedbasis] Constant of continuity : 1.0000000000000018
make a note for this

2022-11-07 16:17 UTC, merged

2022-11-07 16:19 UTC, prudhomm commented
@thomas-saigre I have merged your changes as it fixes things. However could you add some more explanations ?

2022-11-07 16:19 UTC, prudhomm commented
@thomas-saigre I didn't delete the branch, you can still work in it

2022-11-16 14:55 UTC, thomas-saigre commented
@prudhomm I have pushed some modifications in the branch `saigre/pyfeelpp` that needed to be updated and merged, see #222